#%RAML 1.0
title: Loan API
protocols: [ HTTP, HTTPS ]
version: 1.0
description: API to manage the loan payments control system from a fintech
securitySchemes:
  JWT:
    description: Authenticv this to any method that needs a valid JWT to be set.
    type: x-{other}
    describedBy:
      headers:
        Authorization:
          description: X-AuthToken
          type: string
          required: true
      responses:
        401:
          description: Authentication problem (JWT not set or expired)
    settings:
      roles: []
types:
  loan_request:
    type: object
    properties:
      amount: number
      term: integer
      rate: number
      date: 
        type: date-only
    example:      
      amount: 1000
      term: 12
      rate: 0.05
      date: "2019-05-09"
  balance: number
baseUri: http://www.example.com # To be specified
/loans:
  post: 
    description: Insert a new loan request
    body: 
      application/json:
        type: loan_request
        properties:        
          amount: 
            type: number
            example: 1000
          term: 
            description: Mesured in months
            type: integer
            example: 12
          rate: 
            type: number
            description: Indicate float with a dot
            example: 0.5
          date: 
            type: date-only
            example: 2019-05-09     
    responses:
      201:
        description: New loan registered
        headers: 
          Content-Location: 
            example: '/loan/{id}'           
  /{id}/payments:
      description: Payment information for a single loan id
      post:
        body:
          application/json:            
            properties: 
              status:
                pattern: (made|missed)
                example: made
              date: 
                type: date-only
                example: 2019-05-09
              amount: 
                type: number
                example: 150.00
        responses:
          200:
            description: payment registered
          400:
            description: Invalid payment informations
  /{id}/balance:
      description: History of payments for a single id
      get:
        queryParameters:
          date: string
          format: date-only
        responses:
          200:
            body: 
              application/json:                
                type: balance
          400:
            description: 'bad request: informações inválidas'
