#%RAML 1.0
mediaType: application/json
title: Loan API
version: 1.0
description: API to manage the loan payments control system from a fintech
types:
  loan:
    properties:
      amount: number
      term: integer
      rate: number
      date: datetime-only
    example:
      amount: 1000
      term: 12
      rate: 0.05
      date: "2019-05-09T03:18:00"
  id:
    type: string
    pattern: ([0-9]){3}-([0-9]){4}-([0-9]){4}-([0-9]){4}$
    example: 000-0000-0000-0000
  installment: number
  payment_status:
    type: string
    pattern: (made|missed)
    example: made
  balance: number
/loans:
  post:
    description: New loan input
    body: loan
    responses:
      201:
        description: New loan registered
        body:
          properties:
            loan_id: id
            loan_installment: installment
      400:
        description: 'bad request: informações inválidas'
  /{id}:
    description: 'id_format: 000-0000-0000-0000'
    get:
      responses:
        404: 
          body:
            properties:
              error: 
            example:
              error: Loan id not found
        500:
          body:
            properties:
              message: 
            example:
              message: Internal Server Error
        503:
          body:
            properties:
              message: 
            example:
              message: Service temporarily unavailable
    /payments:
      description: Installment input for a single id
      post:
        body:
          properties:
            payment: payment_status
            date: datetime-only
            amount: number
        responses:
          201:
            body:
              properties:
                message: 
              example:
                message: Payment information registered
          400:
            description: bad request
            body:
              properties:
                error:
              example:
                error: Invalid payment informations
    /balance:
      description: History of payments for a single id
      get:
        queryParameters:
          date: string
          format: date-only
        responses:
          200:
            body: balance
          400:
            description: 'bad request: informações inválidas'


