#%RAML 1.0
title: Loans API
version: v1
mediaType: application/json

types:
  Loan:
    properties:
      amount:
        type: number
        format: float
      term:
        type: integer
      rate:
        type: number
        format: float
      date:
        type: datetime
        
  Loan_info:
    properties:
      loan_id:
        type: string
      installment:
        type: number
        format: float
        
  Balance:
    properties:
      date:
        type: datetime
        required: false
        
  LoanBalance:
    properties:
      balance:
        type: number
        format: float
        
  Payment:
    properties:
      payment:
        type: string
      date:
        type: datetime
      amount:
        type: number
        format: float
traits:
  dataValidation:
    responses:
      400:
        description: Parameters received on body request are not valid 
        body:
          properties:
            error: string
            code: string
  uriValidation:
    responses: 
      404:
        description: ID received on uri not found
        body: 
          properties:
            error: string
            code: string

/loan:
  post:
    is: [dataValidation]
    description: Create a new loan. Loans are automatically accepted.
    body:
        type: Loan 
    responses:
        201:
            description: Return the new loan
            body: Loan_info

  '/{id}':
    uriParameters:
      id:
        description: The Loan identifier.
        type: string

    /payment:
      post:
        is: [dataValidation, uriValidation]
        description:  Create a record of a payment made or missed.
        body: 
            type: Payment
        responses:
          201:
            description: ok

    /balance:
      get:
        is: [dataValidation, uriValidation]
        description: 'Get the volume of outstanding LoanBalance (i.e., LoanBalance yet to be paid) at some point in time.'
        body:
          type: Balance                
        responses:
          200:
            description: Outstanding LoanBalance of loan
            body: LoanBalance
                          